name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace "main" with your default branch if it's different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout the code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use your project's Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn

      # Step 4: Build the app
      - name: Build the app
        run: |
          yarn build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
